### ISSUE TITLE
SortaKinda getting locked up with non-exclusive access

### ISSUE THREAD

**Issue by zbee** [MidoriKami/SortaKinda#16]
In the last few days SortaKinda stopped working for me at all with the below error, and I went through numerous attempts to try to fix it, ~~but ultimately it was just because I had an empty Sorting rule.~~

I think this error should be caught and explained to the user -assuming it can be narrowed down, on the assumption that this error would also be thrown if a similar plugin were actually blocking SortaKinda, which is what I tried to find and disable in my trubleshooting-, or empty rules should be deleted on closing them, or simply ignored when running sort.

```
[SortaKinda] Exception Caught During Sorting 'ArmoryEar'
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```

<details><summary>Log when trying to sort manually</summary>

```
01:02:38.562 DBG | [SortaKinda] Sorting Inventory: ArmoryHead
01:02:38.562 DBG | [SortaKinda] Sorting Inventory: ArmoryBody
01:02:38.562 DBG | [SortaKinda] Sorting Inventory: ArmoryHands
01:02:38.562 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.562 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.562 DBG | [SortaKinda] Sorting Inventory: ArmoryLegs
01:02:38.562 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.562 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.562 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.562 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryBody'
01:02:38.562 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryHead'
01:02:38.562 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryHands'
01:02:38.562 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.562 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.562 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.562 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.562 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.562 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.562 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.562 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.562 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR | [SortaKinda] Exception Caught During Sorting 'Inventory1'
01:02:38.562 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.562 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.562 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.562 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.562 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.562 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.562 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.562 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.562 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.562 ERR |    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.562 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.562 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass3_1.<MoveItemsIntoCategories>b__5(IInventorySlot slot) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 60
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.562 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.562 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.562 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.562 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.562 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.562 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.562 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.562 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.562 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.562 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmoryEar
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmoryWrist
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmoryNeck
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmoryRings
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmoryFeets
01:02:38.562 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryOffHand'
01:02:38.562 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.562 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.562 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.562 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.562 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.562 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.562 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.562 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.562 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.562 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.563 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryMainHand'
01:02:38.563 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.563 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.563 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.563 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.563 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.563 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.563 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.563 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.563 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.563 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.563 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.563 DBG | [SortaKinda] Sorting Inventory: ArmorySoulCrystal
01:02:38.563 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryEar'
01:02:38.563 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.563 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.563 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.563 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.563 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.563 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.563 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.563 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.563 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryLegs'
01:02:38.563 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.563 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.563 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.563 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.563 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.563 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.563 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.563 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.563 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryWrist'
01:02:38.563 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.563 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.563 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.563 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.563 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.563 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.563 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.563 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.563 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.563 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.563 DBG | [SortaKinda] Sorted ArmoryNeck in 0.8579ms
01:02:38.563 ERR | [SortaKinda] Exception Caught During Sorting 'ArmoryRings'
01:02:38.563 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.563 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.563 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.563 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.563 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.563 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.563 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.563 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.563 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.563 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.564 ERR | [SortaKinda] Exception Source: SortaKinda :: SortaKinda.System.InventorySorter :: SortInventory
01:02:38.564 DBG | [SortaKinda] Sorted ArmoryFeets in 1.2236ms
01:02:38.564 ERR | [SortaKinda] Exception Caught During Sorting 'ArmorySoulCrystal'
01:02:38.564 ERR | System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
01:02:38.564 ERR |    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
01:02:38.564 ERR |    at SortaKinda.Models.SortingRule.<.ctor>b__3_1(IInventorySlot slot) in /work/repo/SortaKinda/Models/Configuration/SortingRule.cs:line 32
01:02:38.564 ERR |    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
01:02:38.564 ERR |    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
01:02:38.564 ERR |    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
01:02:38.564 ERR |    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
01:02:38.564 ERR |    at System.Linq.OrderedEnumerable`1.ToArray()
01:02:38.564 ERR |    at SortaKinda.System.InventorySorter.MoveItemsIntoCategories(IInventoryGrid[] grids, IReadOnlyCollection`1 rulesForInventory) in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 55
01:02:38.564 ERR |    at SortaKinda.System.InventorySorter.<>c__DisplayClass2_0.<SortInventory>b__0() in /work/repo/SortaKinda/Controllers/Inventory/InventorySorter.cs:line 37
01:02:38.564 ERR |    at KamiLib.NativeUi.Safety.ExecuteSafe(Action action, String message) in /work/repo/KamiLib/UserInterface/NativeUi/Hooking/Safety.cs:line 13
01:02:38.652 DBG | [SortaKinda] Marked ItemODR as changed.
01:02:38.666 DBG | [InventoryTools] 1703232158666 Itemodr reparsedV
```
</details>

[Reproduction dalamud.log](https://github.com/MidoriKami/SortaKinda/files/13749856/dalamud.log)

**Comment by MidoriKami** [comment]
I believe you're misunderstanding the error being logged. It refers to my code making modifications to data that I manage in an improper way. It does not mean that other plugins are doing something to interfere.
